"""
SolarVision AI - PDF Report Generator
Creates professional PDF reports with predictions and visualizations
"""

import os
from pathlib import Path
from datetime import datetime
from io import BytesIO
import base64

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import matplotlib.pyplot as plt
import numpy as np

class PDFReportGenerator:
    """Generate professional PDF reports for batch predictions"""
    
    def __init__(self, output_dir='../outputs'):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#1f4788')
        )
        
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.HexColor('#2c5aa0')
        )
    
    def create_probability_chart(self, probabilities, top_n=6):
        """Create probability bar chart"""
        fig, ax = plt.subplots(figsize=(6, 3))
        
        classes = list(probabilities.keys())
        probs = list(probabilities.values())
        
        # Sort by probability
        sorted_idx = np.argsort(probs)[::-1]
        classes = [classes[i] for i in sorted_idx]
        probs = [probs[i] for i in sorted_idx]
        
        colors_list = ['#2ecc71' if i == 0 else '#3498db' for i in range(len(classes))]
        
        ax.barh(classes[::-1], probs[::-1], color=colors_list[::-1])
        ax.set_xlabel('Probability', fontsize=10)
        ax.set_title('Class Probabilities', fontsize=12, fontweight='bold')
        ax.set_xlim(0, 1)
        
        # Add percentage labels
        for i, (cls, prob) in enumerate(zip(classes[::-1], probs[::-1])):
            ax.text(prob + 0.01, i, f'{prob:.1%}', va='center', fontsize=9)
        
        plt.tight_layout()
        
        # Save to buffer
        buffer = BytesIO()
        plt.savefig(buffer, format='png', dpi=150, bbox_inches='tight')
        buffer.seek(0)
        plt.close()
        
        return buffer
    
    def generate_report(self, predictions, output_filename=None):
        """
        Generate PDF report for batch predictions
        
        Args:
            predictions: List of prediction dictionaries
            output_filename: Optional output filename
            
        Returns:
            Path to generated PDF file
        """
        if output_filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'SolarVision_Report_{timestamp}.pdf'
        
        output_path = self.output_dir / output_filename
        
        # Create document
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        # Container for elements
        elements = []
        
        # Title Page
        elements.append(Paragraph("SolarVision AI", self.title_style))
        elements.append(Paragraph("PV Panel Defect Detection Report", self.styles['Heading2']))
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", 
                                 self.styles['Normal']))
        elements.append(Spacer(1, 0.3*inch))
        
        # Executive Summary
        elements.append(Paragraph("Executive Summary", self.heading_style))
        total_images = len(predictions)
        avg_confidence = np.mean([p['confidence'] for p in predictions if 'confidence' in p])
        
        summary_data = [
            ['Metric', 'Value'],
            ['Total Images Analyzed', str(total_images)],
            ['Average Confidence', f'{avg_confidence:.1%}'],
            ['Detection Model', 'ResNet18 + SVM (96.8% accuracy)'],
            ['Report Generated By', 'SolarVision AI v1.0']
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 3*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5aa0')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(summary_table)
        elements.append(PageBreak())
        
        # Individual Results
        for i, pred in enumerate(predictions, 1):
            if 'error' in pred:
                elements.append(Paragraph(f"Image {i}: Error - {pred['error']}", self.styles['Normal']))
                continue
            
            elements.append(Paragraph(f"Result {i}: {pred['filename']}", self.heading_style))
            
            # Prediction details
            pred_text = f"""
            <b>Predicted Class:</b> {pred['predicted_class']}<br/>
            <b>Confidence:</b> {pred['confidence']:.1%}<br/>
            <b>Top 3 Classes:</b><br/>
            """
            
            for cls, conf in pred['top3']:
                pred_text += f"&nbsp;&nbsp;• {cls}: {conf:.1%}<br/>"
            
            elements.append(Paragraph(pred_text, self.styles['Normal']))
            elements.append(Spacer(1, 0.2*inch))
            
            # Probability chart
            if 'all_probabilities' in pred:
                chart_buffer = self.create_probability_chart(pred['all_probabilities'])
                chart_img = RLImage(chart_buffer, width=5*inch, height=2.5*inch)
                elements.append(chart_img)
            
            elements.append(Spacer(1, 0.3*inch))
            
            # Add page break except for last item
            if i < len(predictions):
                elements.append(PageBreak())
        
        # Footer
        elements.append(Spacer(1, 0.5*inch))
        elements.append(Paragraph(
            "<i>SolarVision AI - Automated PV Panel Defect Detection System</i>",
            ParagraphStyle('Footer', parent=self.styles['Normal'], alignment=TA_CENTER, 
                          textColor=colors.grey)
        ))
        
        # Build PDF
        doc.build(elements)
        
        return str(output_path)
    
    def generate_csv(self, predictions, output_filename=None):
        """
        Generate CSV export of predictions
        
        Args:
            predictions: List of prediction dictionaries
            output_filename: Optional output filename
            
        Returns:
            Path to generated CSV file
        """
        import csv
        
        if output_filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'SolarVision_Predictions_{timestamp}.csv'
        
        output_path = self.output_dir / output_filename
        
        with open(output_path, 'w', newline='') as f:
            if not predictions:
                return str(output_path)
            
            # Get fieldnames from first prediction
            fieldnames = ['filename', 'predicted_class', 'confidence']
            if 'all_probabilities' in predictions[0]:
                fieldnames.extend(predictions[0]['all_probabilities'].keys())
            
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            
            for pred in predictions:
                if 'error' in pred:
                    continue
                
                row = {
                    'filename': pred['filename'],
                    'predicted_class': pred['predicted_class'],
                    'confidence': f"{pred['confidence']:.4f}"
                }
                
                if 'all_probabilities' in pred:
                    for cls, prob in pred['all_probabilities'].items():
                        row[cls] = f"{prob:.4f}"
                
                writer.writerow(row)
        
        return str(output_path)


if __name__ == '__main__':
    # Test generator
    gen = PDFReportGenerator()
    
    # Sample predictions
    sample_preds = [
        {
            'filename': 'test1.jpg',
            'predicted_class': 'Dusty',
            'confidence': 0.942,
            'all_probabilities': {
                'Bird-drop': 0.023,
                'Clean': 0.015,
                'Dusty': 0.942,
                'Electrical-damage': 0.008,
                'Physical-Damage': 0.007,
                'Snow-Covered': 0.005
            },
            'top3': [('Dusty', 0.942), ('Bird-drop', 0.023), ('Clean', 0.015)]
        }
    ]
    
    pdf_path = gen.generate_report(sample_preds)
    print(f"PDF generated: {pdf_path}")
    
    csv_path = gen.generate_csv(sample_preds)
    print(f"CSV generated: {csv_path}")
